[build]
publish = "public"
base = "/"

[dev]
command = "pnpm start:prod"
publish = "public"
targetPort = 8080

[[redirects]]
from = "/contact-me"
to = "/contact"

[[redirects]]
from = "/talks"
to = "/media"

[[redirects]]
from = "/talks/monitorama-pdx-2023"
to = "/talks/monitorama-pdx--monitoring-mastodons-a-story-about-hachyderm-2023"

[[redirects]]
from = "/talks/philly-ete-2023"
to = "/talks/philly-emerging-tech-conference--hacking-the-pachyderm-scaling-servers-and-people-2023"

[[redirects]]
from = "/talks/qcon-sf-2023"
to = "/talks/qcon-san-francisco--understanding-platforms-what-they-are-why-they-work-when-to-use-them-how-to-build-them-2023"

[[redirects]]
from = "/talks/qcon-sf-2023/slides"
to = "/talks/qcon-san-francisco--understanding-platforms-what-they-are-why-they-work-when-to-use-them-how-to-build-them-2023/slides"

[[redirects]]
from = "/talks/sloconf-2023"
to = "/talks/sloconf--motivating-slos-mathematically-2023"

[[redirects]]
from = "/talks/srecon-americas-2023"
to = "/talks/srecon-americas--hacking-the-pachyderm-scaling-servers-and-people-2023"

[[redirects]]
from = "/talks/kubehuddle-2024"
to = "/talks/kubehuddle--not-just-another-dei-panel-2024"

[[redirects]]
from = "/talks/kubecon-na-2024"
to = "/talks/observability-day-kubecon-na--panel-opentelemetry-bridging-platform-and-enablement-2024"

[[redirects]]
from = "/talks/kubecrash-2024"
to = "/talks/kubecrash-fall--feature-flag-all-the-things-2024"

[[redirects]]
from = "/talks/kubecrash-fall-2024--feature-flag-all-the-things/slides/*"
to = "/talks/kubecrash-fall-2024--feature-flag-all-the-things/slides/index.html"
status = 200

[[redirects]]
from = "/talks/virtual-domain-driven-design-meetup-2025--abstractions-as-bridges/slides/*"
to = "/talks/virtual-domain-driven-design-meetup-2025--abstractions-as-bridges/slides/index.html"
status = 200

[[redirects]]
from = "/talks/cfgmgmtcamp-2025--working-configs-humanity-the-real-world-joy-and-happiness-pick-two-ish/slides/*"
to = "/talks/cfgmgmtcamp-2025--working-configs-humanity-the-real-world-joy-and-happiness-pick-two-ish/slides/index.html"
status = 200

[[redirects]]
from = "/talks/linuxfest-northwest-2025--carrying-the-torch-grief-and-remembrance-in-open-source/slides/*"
to = "/talks/linuxfest-northwest-2025--carrying-the-torch-grief-and-remembrance-in-open-source/slides/index.html"
status = 200

[[redirects]]
from = "/talks/linuxfest-northwest-2025--the-geology-of-open-source/slides/*"
to = "/talks/linuxfest-northwest-2025--the-geology-of-open-source/slides/index.html"
status = 200

[[redirects]]
from = "/talks/observability-day-kubecon-eu-2025--operationalizing-observability-the-invisible-parts/slides/*"
to = "/talks/observability-day-kubecon-eu-2025--operationalizing-observability-the-invisible-parts/slides/index.html"
status = 200

[[redirects]]
from = "/talks/platform-engineering-day-kubecon-eu-2025--so-you-want-to-hire-for-platform-engineering/slides/*"
to = "/talks/platform-engineering-day-kubecon-eu-2025--so-you-want-to-hire-for-platform-engineering/slides/index.html"
status = 200

[[redirects]]
from = "/talks/scale-22x-2025--redefining-observability-observability-3-0/slides/*"
to = "/talks/scale-22x-2025--redefining-observability-observability-3-0/slides/index.html"
status = 200

[[redirects]]
from = "/talks/scale-22x-2025--source-available-is-thriving-but-open-source-is-dying/slides/*"
to = "/talks/scale-22x-2025--source-available-is-thriving-but-open-source-is-dying/slides/index.html"
status = 200

[[redirects]]
from = "/talks/ldx3-2025--so-you-want-to-hire-engineering-force-multipliers/slides/*"
to = "/talks/ldx3-2025--so-you-want-to-hire-engineering-force-multipliers/slides/index.html"
status = 200

[[redirects]]
from = "/talks/staffplus-ny-2025--coherent-impact-the-art-of-strategy/slides/*"
to = "/talks/staffplus-ny-2025--coherent-impact-the-art-of-strategy/slides/index.html"
status = 200