backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: blog
    label: Blog
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - label: Publish Date
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
      - { label: "Body", name: body, widget: markdown }
  - name: talks
    label: Talks
    folder: "src/talks"
    create: true
    slug: "{{fields.event}}-{{year}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Event, name: event, widget: string }
      - { label: Location, name: location, widget: string }
      - label: Publish Date
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
      - { label: Abstract, name: abstract, widget: markdown }
      - { label: Slides, name: slides, widget: string, required: false }
      - { label: Talk Page, name: talk_page, widget: string, required: false }
      - { label: Event Site, name: event_site, widget: string, required: false }
      - { label: Video, name: video, widget: string, required: false }
      - { label: "Body", name: body, widget: markdown, required: false }
